# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-20 10:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='album_logo',
            field=models.ImageField(upload_to='', width_field=250),
        ),
    ]
