# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-20 11:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0002_auto_20160720_1409'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='image_height',
            field=models.PositiveIntegerField(blank=True, default='100', editable=False, null=True),
        ),
        migrations.AddField(
            model_name='album',
            name='image_width',
            field=models.PositiveIntegerField(blank=True, default='100', editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='album',
            name='album_logo',
            field=models.ImageField(height_field='image_height', upload_to='', width_field='image_width'),
        ),
    ]
